- hosts: my_pi
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: pruefen ob aktuellste Version
    apt:
      name: apache2
      status: latest
  - name: schreibe Config File
    templates:
      src: apache2.j2
      dest: /etc/apache2.j2
    notify:
    - restart apache
  - name: pruefen ob apache laeuft
      service:
      name: apache2
      state: started
  handlers:
  - name: restart apache
    service:
      name: apache2
      state: restarted